"""Add approval hierarchy

Revision ID: 001b05a4044a
Revises: bc2b64947cf2
Create Date: 2025-04-11 22:24:45.014561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001b05a4044a'
down_revision = 'bc2b64947cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_approver', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('advisor_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dean_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('chairman_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.JSON(), nullable=True))
        batch_op.alter_column('form_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.alter_column('form_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('comments')
        batch_op.drop_column('chairman_status')
        batch_op.drop_column('dean_status')
        batch_op.drop_column('advisor_status')
        batch_op.drop_column('current_approver')

    # ### end Alembic commands ###
