"""Add uh_id

Revision ID: 548dfa51b8d7
Revises: f3d07d2a94fe
Create Date: 2025-04-22 00:12:50.641965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '548dfa51b8d7'
down_revision = 'f3d07d2a94fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_approver', sa.String(length=50), nullable=True))
        batch_op.drop_column('director_status')
        batch_op.drop_column('director_comments')
        batch_op.drop_column('supervisor_timestamp')
        batch_op.drop_column('supervisor_status')
        batch_op.drop_column('counselor_comments')
        batch_op.drop_column('approval_stage')
        batch_op.drop_column('counselor_timestamp')
        batch_op.drop_column('counselor_status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('supervisor_comments')
        batch_op.drop_column('director_timestamp')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uh_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['uh_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uh_id')

    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supervisor_comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('counselor_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('counselor_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approval_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('counselor_comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supervisor_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supervisor_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('director_comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('director_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('current_approver')

    # ### end Alembic commands ###
