"""Add approval workflow fields to AcademicRequests model

Revision ID: ac9efa853e60
Revises: eaf70ce154d3
Create Date: 2025-04-12 16:59:02.719052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac9efa853e60'
down_revision = 'eaf70ce154d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('counselor_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('counselor_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('counselor_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('director_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('director_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('director_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('supervisor_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('form_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('current_approver')
        batch_op.drop_column('college_supervisor_comments')
        batch_op.drop_column('college_supervisor_timestamp')
        batch_op.drop_column('dept_counselor_timestamp')
        batch_op.drop_column('dept_counselor_comments')
        batch_op.drop_column('college_supervisor_status')
        batch_op.drop_column('dept_counselor_status')
        batch_op.drop_column('academic_director_comments')
        batch_op.drop_column('academic_director_timestamp')
        batch_op.drop_column('academic_director_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_director_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('academic_director_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('academic_director_comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_counselor_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('college_supervisor_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_counselor_comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_counselor_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('college_supervisor_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('college_supervisor_comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_approver', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('form_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('supervisor_timestamp')
        batch_op.drop_column('supervisor_comments')
        batch_op.drop_column('supervisor_status')
        batch_op.drop_column('director_timestamp')
        batch_op.drop_column('director_comments')
        batch_op.drop_column('director_status')
        batch_op.drop_column('counselor_timestamp')
        batch_op.drop_column('counselor_comments')
        batch_op.drop_column('counselor_status')
        batch_op.drop_column('approval_stage')

    # ### end Alembic commands ###
