"""Add hierarchical approval support

Revision ID: eaf70ce154d3
Revises: 001b05a4044a
Create Date: 2025-04-12 01:02:11.330033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaf70ce154d3'
down_revision = '001b05a4044a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_counselor_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dept_counselor_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dept_counselor_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('academic_director_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('academic_director_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('academic_director_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('college_supervisor_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_supervisor_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('college_supervisor_timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('current_approver',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('chairman_status')
        batch_op.drop_column('advisor_status')
        batch_op.drop_column('comments')
        batch_op.drop_column('dean_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dean_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('advisor_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chairman_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('current_approver',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('college_supervisor_timestamp')
        batch_op.drop_column('college_supervisor_comments')
        batch_op.drop_column('college_supervisor_status')
        batch_op.drop_column('academic_director_timestamp')
        batch_op.drop_column('academic_director_comments')
        batch_op.drop_column('academic_director_status')
        batch_op.drop_column('dept_counselor_timestamp')
        batch_op.drop_column('dept_counselor_comments')
        batch_op.drop_column('dept_counselor_status')

    # ### end Alembic commands ###
